version: "3.9"

services:
  app:
    build: .
    container_name: post-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: saiful
      POSTGRES_PASSWORD: saiful
      POSTGRES_DB: postdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
